<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:dc="http://purl.org/dc/elements/1.1/"
                version="1.0">
  <xsl:output method="html" encoding="utf-8" />

  <xsl:template match="/">
    <html>
      <head>
	<title>HTML generated by XSLT, List Style</title>
      </head>
      <body>
	<h2>Schedule(List Style)</h2>
	<xsl:apply-templates select="schedules" />
      </body>
    </html>
  </xsl:template>

  <xsl:template match="schedules">
    <xsl:for-each select="schedule">
      <ul>
	<li>
	  タイトル:<xsl:value-of select="metadata/dc:title" />（<xsl:value-of select="@id" />, <xsl:value-of select="@category" />）
	  <ul>
	    <li>
	      場所:<xsl:value-of select="metadata/dc:coverage" />
	    </li>
	    <li>
	      日時:<xsl:value-of select="metadata/dc:date" />
	    </li>
	    <li>
	      備考:<xsl:value-of select="comment" />
	    </li>
	  </ul>
	</li>
      </ul>
    </xsl:for-each>
  </xsl:template>

</xsl:stylesheet>
