<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:dc="http://purl.org/dc/elements/1.1/"
                version="1.0">
  <xsl:output method="html" encoding="utf-8" />

  <xsl:template match="/">
    <html>
      <head>
	<title>HTML generated by XSLT, Table Style</title>
      </head>
      <body>
	<h2>Schedule(Table Style)</h2>
	<xsl:apply-templates select="schedules" />
      </body>
    </html>
  </xsl:template>

  <xsl:template match="schedules">
    <table border="1px">
      <tbody>
	<tr>
	  <th>ID</th>
	  <th>カテゴリ</th>
	  <th>タイトル</th>
	  <th>場所</th>
	  <th>日時</th>
	  <th>備考</th>
	</tr>
	<xsl:for-each select="schedule">
	  <tr>
	    <td>
	      <xsl:value-of select="@id" />
	    </td>
	    <td>
	      <xsl:choose>
		<xsl:when test="@category='Private'">個人</xsl:when>
		<xsl:when test="@category='Meeting'">会議</xsl:when>
		<xsl:when test="@category='PartTimeJob'">バイト</xsl:when>
		<xsl:when test="@category='Lecture'">授業</xsl:when>
	      </xsl:choose>
	    </td>
	    <td>
	      <xsl:value-of select="metadata/dc:title" />
	    </td>
	    <td>
	      <xsl:value-of select="metadata/dc:coverage" />
	    </td>
	    <td>
	      <xsl:value-of select="metadata/dc:date" />
	    </td>
	    <td>
	      <xsl:value-of select="comment" />
	    </td>
	  </tr>
	</xsl:for-each>
      </tbody>
    </table>
  </xsl:template>
  
</xsl:stylesheet>
